bank/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('member-buy/<int:id>/', views.BuyMember.as_view(), name='buymembers'),
    path('payment-transfer/<int:id>/', views.paymenttransfer, name='paymenttransfer'),
    path('payment-credit/<int:id>/', views.paymentcredit, name='paymentcredit'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainpage.urls')),
    path('user/',include('user.urls')),
    path('members/',include('members.urls')),
    path('raffle/',include('raffle.urls')),
    path('buy/',include('bank.urls')),

]

raffle/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('free-raffle/',FreeRaffle.as_view(),name='freeraffle'),
    path('instagram-raffle/',InstagramRaffle.as_view(),name='instagramraffle'),
    path('re-instagram-raffle/',reinstagramraffle,name='reinstagramraffle'),
    path('reference/',reference,name='reference'),
    path('instagram-raffle/result/<int:raffleid>/',InstagramRaffleResult.as_view(),name='instagramraffleresult'),
    path('instagram-raffle/total-comment/',TotalComment.as_view(),name='totalcomment'),
    path('instagram-raffle/raffle-query/',RaffleQuery.as_view(),name='rafflequery'),
]

raffle/models.py
from django.db import models
from django.contrib.auth.models import User
from members.models import Members_Classes

class Raffle(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    user_id = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name='User_id')
    member_id = models.ForeignKey(Members_Classes,on_delete=models.CASCADE, verbose_name='Member_id')
    title = models.CharField(max_length=100,serialize=False, verbose_name='Başlık')
    post_url = models.URLField(verbose_name="Post url")
    username = models.CharField(max_length=100, verbose_name="Username")
    count_a_user = models.BooleanField(verbose_name='Kullanıcı bir kere sayılsın')
    tag = models.IntegerField(verbose_name='Etiket Sayısı')
    text_list = models.TextField(null=True,verbose_name='Yorumda olması gereken yazılar')
    follow_list = models.TextField(null=True,verbose_name='Takip etmesi gerekenler')
    main_user_list = models.TextField(verbose_name='Tüm yapılan yorumlar')
    winner = models.IntegerField(verbose_name='Kazanan Sayısı')
    backup_winner = models.IntegerField(verbose_name='Yedek Sayısı')
    animate_time = models.IntegerField(verbose_name='Animasyon süresi')
    date = models.DateTimeField(auto_now_add=True, blank=True)
    status = models.BooleanField(default=True,verbose_name='Durum')

    def __str__(self) -> str:
        return str(self.username)

class Raffle_Result(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    raffle_id = models.ForeignKey(Raffle,on_delete=models.CASCADE,verbose_name='Çekiliş Numarası')
    winner_list = models.TextField(verbose_name='Kazanan listesi')
    backup_list = models.TextField(verbose_name='Yedek listesi')
    valid_user_list = models.TextField(verbose_name='Filtrelenmiş kullanıcı listesi')
    animate_status = models.BooleanField(default=True,verbose_name='Animasyon Durum')
    status = models.BooleanField(default=True,verbose_name='Durum')
    
    def __str__(self) -> str:
        return str(self.raffle_id)
        
# class Raffle_User_Member(models.Model):
#     id = models.BigIntegerField(primary_key=True, auto_created=True,serialize= False, verbose_name='ID')
#     raffle_id = models.ForeignKey(Raffle,on_delete=models.CASCADE, verbose_name='Çekiliş Numarası')
#     user_id = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name='')
#     member_id = models.ForeignKey(Members_Classes,on_delete=models.CASCADE, verbose_name='')
#     date = models.DateTimeField(auto_now_add=True, blank=True)
#     status =models.BooleanField(default=True,verbose_name='Durum')

raffle/views.py
import json
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
import random
from django.views.generic import View
from members.models import Members_Classes, User_Member_Class
from .models import Raffle, Raffle_Result
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import naturaltime
import os

def userform(userid):
    user_members = User_Member_Class.objects.filter(
        status=True, user_id=userid)

    if (len(user_members) == 0):
        return False
    else:
        member = []
        membername = []
        for mem in user_members:
            member.append(mem.member_id)

        for memid in member:
            m = Members_Classes.objects.get(name=str(memid))
            membername.append({'id': str(m.id), 'name': str(
                m.name), 'comment': str(m.coment_limit)})
        return membername


class ConvertList():
    import json

    def __init__(self, list):
        self.list = list

    def convert(self):
        if self.list != '':
            list_convert = str(self.list)
            check = "\/"
            for c in check:
                list_convert = list_convert.replace(c, "")
            list_convert = list_convert.replace("'", '"')
            list_dumps = json.dumps(list_convert)
            list_loads = json.loads(list_dumps)
            result = json.loads(list_loads)
            return result
        else:
            return ''


class Result:
    # coding=utf-8
    def __init__(self, mainlist, winner, backup, insta) -> None:
        self.winner = winner
        self.backup = backup
        self.list = mainlist
        self.backupnumber = self.backup
        self.winlist = []
        self.backuplist = []
        self.info = ''
        self.insta = insta

        self.checkwinner = []
        self.checkbackup = []

    def result(self):
        if self.backup != 0:

            self.number = len(self.list)-int(self.winner)

            if 0 < self.number < int(self.backup):
                self.backupnumber = self.number
                self.info = 'Liste sayısı az olduğundan yedek listesi kalan kullanıcılardan rasgele seçilerek sıralandı.'
                if self.insta == True:
                    Result.instaraffle(self)
                else:
                    Result.raffle(self)
                return {'winnerlist': self.winlist, 'backuplist': self.backuplist, 'info': self.info}

            elif self.number == 0:
                if self.insta == True:
                    Result.instaraffle(self)
                else:
                    Result.raffle(self)
                    self.info = 'Kazananlar ile liste eşit olduğundan yedek kişi seçilemedi.'
                return {'winnerlist': self.winlist, 'backuplist': self.backuplist, 'info': self.info}

            elif self.number < 0:
                self.info = 'Kazanan sayısı listedeki kişi sayısını geçemez.'
                return {'winnerlist': self.winlist, 'backuplist': self.backuplist, 'info': self.info}

            else:
                if self.insta == True:
                    Result.instaraffle(self)
                else:
                    Result.raffle(self)
                return {'winnerlist': self.winlist, 'backuplist': self.backuplist, 'info': self.info}

        else:
            if len(self.list) < int(self.winner):
                self.info = 'Kazanan sayısı listedeki kişi sayısını geçemez.'
                return {'winnerlist': self.winlist, 'backuplist': self.backuplist, 'info': self.info}
            else:
                if self.insta == True:
                    Result.instaraffle(self)
                else:
                    Result.raffle(self)
                return {'winnerlist': self.winlist, 'backuplist': self.backuplist, 'info': self.info}

    def raffle(self):
        for i in range(int(self.winner)):
            while True:
                user = random.choice(self.list)
                if user not in self.winlist:
                    self.winlist.append(user)
                    break

        if self.backup != 0:
            if self.backupnumber != self.backup:
                for i in range(int(self.backupnumber)):
                    while True:
                        user = random.choice(self.list)
                        if user not in self.winlist:
                            if user not in self.backuplist:
                                self.backuplist.append(user)
                                break

            elif self.backupnumber == self.backup:
                for i in range(int(self.backup)):
                    while True:
                        draw = random.choice(self.list)
                        if draw not in self.winlist:
                            if draw not in self.backuplist:
                                self.backuplist.append(draw)
                                break

    def instaraffle(self):
        for i in range(int(self.winner)):
            while True:
                user = random.choice(self.list)
                if user['userid'] not in self.checkwinner:
                    self.checkwinner.append(user['userid'])
                    self.winlist.append(user)
                    break

        if self.backup != 0:
            if self.backupnumber != self.backup:
                for i in range(int(self.backupnumber)):
                    while True:
                        user = random.choice(self.list)
                        if user['userid'] not in self.checkwinner:
                            if user['userid'] not in self.checkbackup:
                                self.checkbackup.append(user['userid'])
                                self.backuplist.append(user)
                                break

            elif self.backupnumber == self.backup:
                for i in range(int(self.backup)):
                    while True:
                        user = random.choice(self.list)
                        if user['userid'] not in self.checkwinner:
                            if user['userid'] not in self.checkbackup:
                                self.checkbackup.append(user['userid'])
                                self.backuplist.append(user)
                                break


class TextareaConvert:
    def __init__(self, text) -> None:
        self.text = str(text).split(',')
        self.newtext = []

    def convert(self):
        for follow in self.text:
            convert = str(follow).replace("\n", "")
            convert = convert.replace("\r", "")
            if convert != '':
                self.newtext.append(convert)
        return self.newtext


class FreeRaffle(View):
    def get(self, request):
        getraffle = Raffle.objects.filter(status = True).order_by('-id')[:4][::1]
        mainlist=[]
    
        for ge in getraffle:
            main = ConvertList(ge.main_user_list).convert()
            mainlist.append({'id':ge.id,'username':ge.username,'post_url':ge.post_url,'winner':ge.winner,'date':ge.date})
        raffle = Raffle.objects.all()
        totalcomment = 0
        totalwinner = 0

        for raf in raffle :
            totalcomment += len(ConvertList(raf.main_user_list).convert())
            totalwinner += raf.winner
        context = {
            'raffle':mainlist,
            'totalraffle':len(raffle),
            'totalcomment':totalcomment,
            'totalwinner':totalwinner,
        }
        return render(request, 'raffle/freeraffle.html',context=context)
        

    def post(self, request):
        self.title = request.POST.get('title')
        self.winner = request.POST.get('winner')
        self.raffle = request.POST.get('list')
        self.backup = request.POST.get('backup')
        self.raffle = TextareaConvert(self.raffle).convert()

        result = Result(winner=self.winner, mainlist=self.raffle,
                        backup=self.backup, insta=False).result()
        winnerlist = result['winnerlist']
        backuplist = result['backuplist']
        info = result['info']
        listlen = len(self.raffle)

        if request.is_ajax():
            return JsonResponse({'raffle_list': self.raffle, 'title': self.title, 'winner': winnerlist, 'backupwin': backuplist, 'info': info, 'len': listlen}, status=200)

        return render(request, 'raffle/freeraffle.html')


class TotalComment(View):
    def get(self, request):
        return redirect('index')

    def post(self, request):
        self.url = request.POST.get('posturl')
        self.username = request.POST.get('username')
        if request.is_ajax():
            try:
                import instaloader
                insta = instaloader.Instaloader()
                profile = instaloader.Profile.from_username(
                    insta.context, str(self.username))
                posts = profile.get_posts()
                for post in posts:
                    if post.shortcode in self.url:
                        comment = post.comments
                        break
                return JsonResponse({'totalcomment': comment}, status=200)
            except:
                comment = 'Hata! "Username" ya da "Gönderi Link" bilgilerini kontrol ediniz.'
                return JsonResponse({'totalcomment': comment}, status=200)
        if request.user.is_authenticated:
            current_user = request.user.id
            member = userform(current_user)
            if member == False:
                info = 'Bir Paket Satın Al'
                return render(request, 'raffle/instagramraffle.html', {'info': info})
            else:
                return render(request, 'raffle/instagramraffle.html', {'member': member})
        return render(request, 'raffle/instagramraffle.html')


class InstagramRaffle(View):
    def get(self, request):
        getraffle = Raffle.objects.filter(status=True).order_by('-id')[:4][::1]
        mainlist = []

        for get in getraffle:

templates/raffle/freeraffle.html
{% extends "layout.html" %} {% load static %} {% block head %}
<title>Ücretsiz Çekiliş</title>
{% endblock head %} {% block body %}

<div class="main-in">
    <div class="d-flex justify-content-center">
        <form id="freeraffleinstagram" class="raffle-form">
            <div class="card-form text-center">
                <div class="card-header text-dark text-center">
                    <h5 class="card-title">Ücretsiz Çekiliş </h5>
                </div>
                <div class="card-body pt-5">
                    {% csrf_token %}
                    <div class="input-group row">
                        <div class="col-12">
                            <label for="id_title" class="form-label">
                                <h5>Çekiliş Adı
                            </label>
                        </div>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" name="title" id="id_title" placeholder="Çekiliş Adı" required>
                        </div>
                    </div>

                    <div class="input-group row pt-3">
                        <div class="col-12">
                            <label for="id_list" class="form-label">
                                <h5>Çekiliş Listesi</h5>
                            </label>
                        </div>
                        <div class="col-sm-12">
                            <textarea class="form-control" onkeypress="onTestChange();" name="list" id="id_list" rows="5" placeholder="Çekiliş listesi"></textarea>
                        </div>
                        <div class="col-sm-12 alert alert-dismissible fade show" role="alert">
                            <strong>Not :</strong> Her kullanıcıdan sonra 'enter' tuşuna basın ya da toplu liste için her kulanıcı arasında virgül olmasına dikkat edin.
                        </div>
                    </div>

                    <div class="input-group row pt-3">
                        <div class="col-12">
                            <label for="id_winner" class="form-label">
                                <h5>Kaç Kazanan Olsun</h5>
                            </label>
                        </div>
                        <div class="col-sm-12 ">
                            <input type="number" class="form-control" name="winner" id="id_winner" placeholder="Kazanan Sayısı:" min='1' required=" required ">
                        </div>
                    </div>

                    <div class="input-group row pt-3">
                        <div class="col-12">
                            <label for="id_backup" class="form-label">
                                <h5>Kaç Yedek olsun</h5>
                            </label>
                        </div>
                        <div class="col-sm-12">
                            <input type="number" class="form-control" name="backup" id="id_backup" placeholder="Yedek Sayısı:" min='0' required=" required ">
                        </div>
                    </div>
                    <div class="row">
                        <div class="d-grid gap-2 col-8 mx-auto pt-5">
                            <button type="submit" id="free-raffle-btn" class="btn submit-btn">Çekilişi Başlat</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="container">
        <div class="load-container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <div class="spinner-border text-warning" role="status" style="width: 100px;height: 100px; ">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                    <h3 id="load-container-text" class="text-text">Lütfen bekleyiniz... Verileriniz işleniyor</h3>
                </div>
            </div>
        </div>

        <div class="raffle-result-comment">

            <div class="d-flex flex-column bd-highlight align-items-center mb-3">

                <div class="p-2 bd-highlight">
                    <h1 id="main-title"></h1>
                </div>

                <div class="p-2 bd-highlight">
                    <h2 class='pt-3' id="result-title-len"></h2>
                </div>
             
                <div class="p-2 bd-highlight">
                    <div class="info alert alert-warning alert-dismissible fade show" role="alert">
                        <h5 id="info"></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            </div>
        </div>

        <div class="raffle-result-container" id="winner">
            <hr class="hr">
                <div class="d-flex flex-column p-2 mb-3 align-items-center">
                    <div class="p-3 bd-highlight">
                        <p class="main-title ">ASİL KAZANANLAR
                        </p>
                    </div>
            </div>  
            <div class="d-flex flex-wrap bd-highlight mb-3 justify-content-center result-card">

            </div>
        </div>


        <div class="raffle-backup-container" id="backup">
            <hr class="hr">
            <div class="d-flex flex-column p-2 mb-3 align-items-center">
                <div class="p-3 bd-highlight">
                    <p class="main-title ">YEDEK KAZANANLAR
                    </p>
                </div>
            </div>
            <div class="d-flex flex-wrap bd-highlight mb-3 justify-content-center result-backup-card">

            </div>

        </div>
    </div>

    <div class="container main-top-bot">
        <div class="d-flex flex-row bd-highlight mb-3 justify-content-center">
            <div class="p-2 bd-highlight">
                <h1 class="main-title">Neler Yapıldı ?</h1>
            </div>
            <br>
        </div>
        <div class="d-flex flex-wrap bd-highlight d-sm-flex mb-3 justify-content-center">
            <div class="p-2 bd-highlight">
                <div class="">
                    <div class="card-body text-center">
                        <h5 class="pt-2"><i class="fas fa-gifts colorsubmit" style="font-size: 50px"></i></h5>
                        <h2 class="title-color pt-2">Toplam Çekiliş</h2>
                        <h3 class="text-color pt-2">{{totalraffle}}</h3>
                    </div>
                </div>
            </div>
            <div class="p-2 bd-highlight">
                <div class="">
                    <div class="card-body text-center">
                        <h5 class="pt-2"><i class="fas fa-users colorsubmit" style="font-size: 50px;"></i></h5>
                        <h2 class="title-color pt-2">Toplam Katılımcı</h2>
                        <h3 class="text-color pt-2">{{totalcomment}}</h3>
                    </div>
                </div>
            </div>
            <div class="p-2 bd-highlight">
                <div class="">
                    <div class="card-body text-center">
                        <h5 class="pt-2"><i class="fas fa-trophy colorsubmit" style="font-size: 50px;"></i></h5>
                        <h2 class="title-color pt-2">Toplam Kazanan</h2>
                        <h3 class="text-color pt-2">{{totalwinner}}</h3>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="d-flex flex-row bd-highlight pb-5 pt-5 justify-content-center">
        <div class="p-2 bd-highlight">
            <h1 class="main-title text-center">En Son Yapılan Çekilişler</h1>
        </div>
        <br>
    </div>
    <div class="d-flex flex-wrap bd-highlight d-sm-flex pb-5 pt-5 justify-content-center">
        {% for raff in raffle %}
        <div class="p-3 bd-highlight">
            <div class="reference-card-result" style="width: 15rem;">
                <div class="card-body text-center">
                    <a id="ref-href" target="_blank" href="{{raff.post_url}}">
                        <img src={% static 'profilepic/' %}{{raff.id}}/{{raff.username}}.jpg class="card-img-top" alt="profil pictures"></a>
                    <h5 class="reference-card-text card-username pt-2">{{raff.username}}</h5>
                    <p class="reference-card-text card-post">
                        <a class="reference-link-href" target="_blank" rel="noopener noreferrer" href="{{raff.post_url}}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-instagram link-href" viewBox="0 0 16 16">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                            </svg>
                        </a>
                    </p>
                    <p class="reference-card-text card-winner">Kazanan : {{raff.winner}}</p>
                    <p class="reference-card-date card-date">{{raff.date|timesince}}</p>
                    <a href="{% url 'instagramraffleresult' raff.id %}" class="btn get-btn">İncele</a>
                </div>
            </div>
        </div>
        {% endfor %}
        
    </div>
    <div class="d-flex flex-wrap bd-highlight d-sm-flex pb-5 pt-5 justify-content-center ">
        <div class="p-3 bd-highlight ">
            <a href="{% url 'reference' %}" class="btn submit-btn">Daha Fazla Görüntüle</a>
        </div>
    </div>
    

</div>











{% endblock body %} {% block script %}
<script src="{% static 'script/freeraffle.js' %}"></script>

{% endblock script %}

templates/raffle/reference.html
{% extends "layout.html" %} {% load static %} {% block head %}
<title> Referanslar </title>
{% endblock head %} {% block body %}

<div class="main-in">

    <div class="d-flex flex-row bd-highlight mb-3 justify-content-center">
        <div class="p-2 bd-highlight">
            <h1 class="main-title">REFERANSLAR</h1>
        </div>
        <br>
    </div>

    <div class="d-flex flex-row p-2 justify-content-center text-center pt-3 pb-3" style="float:none;margin:auto">
        <div class="p-3 bd-highlight">
            <p>
                <button class="btn get-btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Çekiliş Sorgulama
            </button>
            </p>
            <div class="collapse" id="collapseExample">
                <div class="card-form">
                    <form id='query-raffle'>
                        {% csrf_token %}
                        <div class="card-body">
                            <label for="id_raffleid" class="col-sm-12 col-form-label">
                            <h5>Çekiliş Numarası</h5>
                        </label>
                            <input type="number" min="0" class="form-control" name="raffleid" id="id_raffleid" placeholder="Çekiliş Numarası" required>
                        </div>
                        <div class="card-body">
                            <button type="submit" class="btn get-btn ">Sorgula</button>
                        </div>
                        <div class="card-body">
                            <div id='spinner' class="col-12 text-center pt-1" role="alert">
                                <div class="spinner-border text-info" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                                <p> Veri alınıyor.. </p>
                            </div>
                            <div class="reference-query-alert">

                            </div>
                        </div>

                    </form>
                </div>
            </div>

            <div id="query-result" class="row">

            </div>
        </div>
    </div>

        <div class="d-grid gap-2 col-8 mx-auto">
        <hr class="hr">
    </div>

    <div class="d-flex flex-row bd-highlight mb-3 justify-content-center">
        <div class="p-2 bd-highlight">
            <h1 class="main-title">YAPILAN ÇEKİLİŞLER</h1>
        </div>
        <br>
    </div>



    <div class="d-flex flex-wrap bd-highlight d-sm-flex mb-3 justify-content-center">
        {% for raff in raffle %}
        <div class="p-3 bd-highlight">
            <div class="reference-card-result" style="width: 15rem;">
                <div class="card-body text-center">
                    <a id="ref-href" target="_blank" href="{{raff.post_url}}">
                        <img src={% static 'profilepic/' %}{{raff.id}}/{{raff.username}}.jpg class="card-img-top" alt="profil pictures"></a>
                    <h5 class="reference-card-text card-username pt-2">{{raff.username}}</h5>
                    <p class="reference-card-text card-post">
                        <a class="reference-link-href" target="_blank" rel="noopener noreferrer" href="{{raff.post_url}}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-instagram link-href" viewBox="0 0 16 16">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                        </svg>
                        </a>
                    </p>
                    
                    <p class="reference-card-text card-winner">Kazanan : {{raff.winner}}</p>
                    <p class="reference-card-date card-date">{{raff.date|timesince}}</p>
                    <a href="{% url 'instagramraffleresult' raff.id %}" class="btn get-btn">İncele</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock body %} {% block script %}
<script src="{% static 'script/reference.js' %}"></script> {% endblock script %}